In [2]:
import streamlit as st
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    '1列目': [1, 2, 3, 4],
    '2列目': [10, 20, 30, 40]
})

In [3]:
df

   1列目  2列目
0    1   10
1    2   20
2    3   30
3    4   40

In [3]:
df = pd.DataFrame(
    np.random.rand(20, 3),
    columns=['a', 'b', 'c']
)
df

           a         b         c
0   0.137743  0.570276  0.141335
1   0.727294  0.316538  0.831585
2   0.445560  0.774253  0.797403
3   0.392388  0.030125  0.122603
4   0.781944  0.367252  0.263502
5   0.441613  0.608866  0.103436
6   0.099474  0.553576  0.943812
7   0.772347  0.446709  0.366528
8   0.074063  0.316374  0.018395
9   0.082284  0.040711  0.705291
10  0.769182  0.326892  0.989509
11  0.200867  0.236220  0.458195
12  0.035696  0.096086  0.346417
13  0.316112  0.192375  0.637388
14  0.740268  0.105012  0.840573
15  0.096607  0.150678  0.833483
16  0.759531  0.150976  0.437301
17  0.819427  0.971131  0.329020
18  0.539329  0.777652  0.814327
19  0.767355  0.779106  0.985532

In [13]:
df = pd.DataFrame(
    np.random.rand(100, 2)/[50, 50] + [35.69, 139.70],
    columns=['lat', 'lon']
)
df

          lat         lon
0   35.690418  139.719347
1   35.699095  139.709154
2   35.690318  139.707167
3   35.697669  139.709488
4   35.696922  139.703738
..        ...         ...
95  35.706117  139.703181
96  35.707114  139.700274
97  35.693755  139.704356
98  35.690649  139.707606
99  35.697060  139.703563

[100 rows x 2 columns]

In [14]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]